name = "ai-assistant-worker"
main = "src/worker.py"
compatibility_flags = ["python_workers"]
compatibility_date = "2024-01-29"

[vars]
CF_ACCOUNT_ID = "5f48b4de3583a076c4ea43392167b6f9"
CF_AI_GATEWAY_ID = "ai-assistant"