services:
  cms:
    build:
      context: ./systems/cms
      dockerfile: Dockerfile
      target: base
    command: ./scripts/docker/start.sh
    entrypoint: /bin/sh
    environment:
      - CMS_BASE_URL=http://localhost:4001/
    volumes:
      - source: ./systems/cms/content
        target: /app/content
        type: bind
      - source: ./systems/cms/public/uploads
        target: /app/public/uploads
        type: bind
      - source: ./systems/cms/tina/tina-lock.json
        target: /app/tina/tina-lock.json
        type: bind
  web:
    build:
      context: systems/web
      dockerfile: Dockerfile
      target: base
    command: ./scripts/docker/start.sh
    depends_on:
      cms:
        condition: service_healthy
    entrypoint: /bin/sh
    environment:
      - WEB_CMS_BASE_URL=http://cms:4001/
      - WEB_BASE_URL=http://localhost:4321/
