services:
  cms:
    command: ./scripts/docker/start.sh --test
    ports:
      - '4001:4001'
  tests:
    build:
      context: systems/tests
      dockerfile: Dockerfile
      target: base
    command: ./scripts/docker/start.sh
    depends_on:
      cms:
        condition: service_healthy
      web:
        condition: service_healthy
    entrypoint: /bin/bash
    environment:
      - TESTS_WEB_BASE_URL=http://localhost:4321/
      - TESTS_CMS_BASE_URL=http://localhost:4001/
  web:
    command: ./scripts/docker/start.sh --test
    ports:
      - '4321:4321'