services:
  cms:
    command: ./scripts/docker/start.sh --test
  tests:
    build:
      context: systems/tests
      dockerfile: Dockerfile
      target: base
    command: ./scripts/docker/start.sh
    depends_on:
      cms:
        condition: service_healthy
      web:
        condition: service_healthy
    entrypoint: /bin/bash
    environment:
      - TESTS_WEB_BASE_URL=http://web:4321
      - TESTS_CMS_ENDPOINT=http://cms:4001/graphql
  web:
    command: ./scripts/docker/start.sh --test