services:
  cms:
    build:
      context: ./systems/cms
      dockerfile: Dockerfile
      target: base
    command: ./scripts/docker/start.sh
    develop:
      watch:
        - action: sync
          ignore:
            - systems/cms/tina/__generated__
            - systems/cms/tina/tina-lock.json
          path: systems/cms/tina
          target: /app/tina
        - action: rebuild
          path: systems/cms/package.json
        - action: rebuild
          path: systems/cms/package-lock.json
        - action: rebuild
          path: systems/cms/tsconfig.json
    entrypoint: /bin/sh
  web:
    build:
      context: systems/web
      dockerfile: Dockerfile
      target: base
    command: ./scripts/docker/start.sh
    depends_on:
      cms:
        condition: service_healthy
    entrypoint: /bin/sh
    environment:
      - WEB_CMS_BASE_URL=http://cms:4001/
