services:
  cms:
    command: ./scripts/docker/start.sh --build
  resume-builder:
    build:
      context: systems/resume
      dockerfile: Dockerfile
      target: base
    command: ./scripts/docker/build.sh
    depends_on:
      web:
        condition: service_healthy
    entrypoint: /bin/bash
    environment:
      VITE_RESUME_SOURCE: http://web:4321/portfolio/resume.json
    volumes:
      - bind:
          create_host_path: true
        source: ./dist
        target: /app/dist
        type: bind
  web:
    command: ./scripts/docker/build.sh
    environment:
      WEB_STRIPE_PUBLISHABLE_KEY: ${WEB_STRIPE_PUBLISHABLE_KEY}
      WEB_STRIPE_SECRET_KEY: ${WEB_STRIPE_SECRET_KEY}
    volumes:
      - bind:
          create_host_path: true
        source: ./dist
        target: /app/dist
        type: bind