env:
  CI: true
jobs:
  deploy:
    environment:
      name: main
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash ./scripts/ci/build.sh
      - name: Upload doc folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./systems/web/dist
      - id: deployment
        name: Deploy static site to GitHub Pages
        uses: actions/deploy-pages@v4
name: deploy-github-page-after-push-main

on:
  push:
    branches:
      - main
permissions:
  contents: write
  id-token: write
  pages: write