env:
  CI: true

jobs:
  deploy:
    environment: main
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          WEB_STRIPE_PUBLISHABLE_KEY: ${{secrets.WEB_STRIPE_PUBLISHABLE_KEY}}
          WEB_STRIPE_SECRET_KEY: ${{secrets.WEB_STRIPE_SECRET_KEY}}
        name: Build website to static assets
        run: bash ./scripts/ci/build.sh
      - name: Upload dist folder
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist
      - id: deployment
        name: Deploy static site to GitHub Pages
        uses: actions/deploy-pages@v4
name: deploy-github-page-after-push-main

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: write
  id-token: write
  pages: write