env:
  CI: true
  HUSKY: 0
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
      - name: Use Node.js LTS
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: .nvmrc
      - run: bash ./scripts/setup.sh
      - run: bash ./scripts/ci/test.sh
name: Verify PR

on: pull_request
